src/Entity/Dish.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\DishRepository")
 */
class Dish
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Calories;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\Length(
     *     min=10,
     *     max=100),
     *      minMessage = "La description d'un plat doit contenir plus de {{ limit }} caractères",
     *      maxMessage = "La description d'un plat doit contenir moins de {{ limit }} caractères"
     */
    private $Description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Sticky;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="dishes")
     */
    private $Category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="dishes")
     */
    private $User;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Allergen", mappedBy="Dishes")
     */
    private $allergens;

    public function __construct()
    {
        $this->allergens = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getCalories(): ?int
    {
        return $this->Calories;
    }

    public function setCalories(?int $Calories): self
    {
        $this->Calories = $Calories;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(?float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getSticky(): ?bool
    {
        return $this->Sticky;
    }

    public function setSticky(bool $Sticky): self
    {
        $this->Sticky = $Sticky;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection|Allergen[]
     */
    public function getAllergens(): Collection
    {
        return $this->allergens;
    }

    public function addAllergen(Allergen $allergen): self
    {
        if (!$this->allergens->contains($allergen)) {
            $this->allergens[] = $allergen;
            $allergen->addDish($this);
        }

        return $this;
    }

    public function removeAllergen(Allergen $allergen): self
    {
        if ($this->allergens->contains($allergen)) {
            $this->allergens->removeElement($allergen);
            $allergen->removeDish($this);
        }

        return $this;
    }

    public function __toString(){
        return $this->Name;
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Dish;
use Doctrine\DBAL\Exception\DatabaseObjectNotFoundException;
use Doctrine\DBAL\Exception\DriverException;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

use App\Entity\User;

use App\Service\RandomSlogan;

class FrontController extends Controller
{
    /**
     * @Route("/", name="front_home")
     */
    public function index()
    {
        return $this->render('front/index.html.twig', [
            'controller_name' => 'FrontController',
            "page_title" => "Bienvenue"
        ]);
    }

    /**
     * @Route("/equipe", name="front_team", methods = {"GET"})
     */
    public function equipe(RandomSlogan $rdmsl)
    {
        $rhService = $this->get('restau.services.rh');

        $team = $rhService->getDayTeam(\date('Y-m-d'));

        if (!$team) {
            throw $this->createNotFoundException(
                'No user found'
            );
        }

        return $this->render('front/equipe.html.twig', [
            'controller_name' => 'FrontController',
            'team' => $team,
            'slogan' => $rdmsl->getSlogan(),
            "page_title" => "Notre equipe"
        ]);
    }

    /**
     * @Route("/equipe/insert", name="insert_form", methods = {"GET"})
     */
    public function insert_user()
    {
        $form = $this->createFormBuilder()
            ->add('username', TextType::class)
            ->add('firstname', TextType::class)
            ->add('lastname', TextType::class)
            ->add('email', TextType::class)
            ->add('jobtitle', TextType::class)
            ->add('submit', SubmitType::class, array('label' => 'Valider'))
            ->setMethod('GET')
            ->setAction($this->generateUrl('admin_team_insert'))
            ->getForm();

        return $this->render('front/form_insert.html.twig', array(
            'form' => $form->createView(),
            "page_title" => "Créer un utilisateur"
        ));
    }

    /**
     * @Route("/carte", name="front_dishes", methods = {"GET"})
     */
    public function carte()
    {
        $categories = $this->getDoctrine()->getRepository(Category::class)->getCategoriesWithNbDishes();

        return $this->render('front/front_carte.html.twig', array(
            'categories' => $categories,
            "page_title" => "Carte du restaurant"
        ));

    }

    /**
     * @Route("/carte/{id_category}", name="front_dishes_category", methods = {"GET"})
     */
    public function front_dishes_category($id_category)
    {
        $category = $this->getDoctrine()->getRepository(Category::class)->find($id_category);

        if(!empty($category)){
            $dishes = $this->getDoctrine()->getRepository(Dish::class)->findBy([
                "Category" => $category
            ]);

            return $this->render('front/front_carte_category.html.twig', array(
                'dishes' => $dishes,
                "cat" => $category,
                "page_title" => "Carte des ".$category->getName()
            ));
        }else{
            throw $this->createNotFoundException("Pas de catégorie correspondante.");
        }

    }

    /**
     * @Route("/mentions-legales", name="front_legals", methods={"GET"})
     */
    public function mentions()
    {
        return $this->render('front/mentions.html.twig', [
            "page_title" => "Mentions légales"
        ]);
    }

}

templates/front/equipe.html.twig
{% extends 'layout/front-office.html.twig' %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="team-wrapper">
        <h1>TEAM ✅</h1>
        <h2>These is our crew:</h2>
        <ul>
            {% for user in team %}
                <li>{{ user }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/front/front_carte.html.twig
{% extends 'layout/front-office.html.twig' %}

{% block body %}
    <ul>
        {% for cat in categories %}
            <li><a href="{{ path('front_dishes_category', {"id_category": cat.id}) }}">{{ cat.name }} <span class="nb_dishes"> ( {{ cat.nb }} )</span></a></li>
        {% endfor %}
    </ul>
{% endblock %}

templates/front/front_carte_category.html.twig
{% extends 'layout/front-office.html.twig' %}

{% block title %} {{ cat.name }} {% endblock %}

{% block body %}
    <h1>{{ cat.name }}</h1>

    <ul>
    {% for dish in dishes %}
        <li>{{ dish.name }} - {{ dish.price }}€  ({{ dish.calories }} Kcal)</li>
        {% if dish.allergens|length > 0 %}
            <h3>Allergene(s)</h3>
            <ul>
                {%  for allergen in dish.allergens %}
                    <li>
                        {{ allergen.name }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endfor %}
    </ul>

    <a id="link_return" href="{{ path('front_dishes') }}">Retour</a>
{% endblock %}

templates/front/index.html.twig
{% extends 'layout/front-office.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
<nav>
    <ul>
        <li><a href="/equipe">Notre team</a></li>
    </ul>
</nav>

<section>
    {{ render(controller('App\\Controller\\BlockController::dayDishesAction',
        { 'max': 3 })) }}
</section>
{% endblock %}

templates/front/mentions.html.twig
{% extends 'layout/front-office.html.twig'%}

{% block title %}
    <title>Mentions légales</title>
{% endblock %}
{% block body %}
    <h1>Mentions </h1>
{% endblock body %}